import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from '@/components/Header/Header'
import './globals.css'

const GeistMono = localFont({
  src: [
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-UltraBlack.woff2',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-Black.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-Thin.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Mono/GeistMono-UltraLight.woff2',
      weight: '100',
      style: 'normal',
    },
  ],
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${GeistMono.className} mx-auto min-h-screen max-w-[1200px] text-balance pb-16`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
